import { SPEED_MULTIPLIER } from './game'

export const SHOW_WEIGHTS = true

export const WEIGHT_ROW_INCREMENT = 0.25
export const WEIGHT_ROW_DECREMENT_FACTOR = 0.01

export const SPAWNING_ZOMBIE_TIMER_TRESHOLD = [5500, 28000]
export const DECREMENT_PER_SPAWN = 500
export const SPAWNING_HORDE_TIMER = 900 * SPEED_MULTIPLIER
